name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cached_network_image: ^3.4.1
  core:
    path: ../core
  # image_cropper: ^7.0.5
  crop_image: ^1.0.16
  currency_text_input_formatter: ^2.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  modal_bottom_sheet: ^3.0.0
  pasteboard: ^0.4.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^9.0.0

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # - family: Lora
    #   fonts:
    #     - asset: assets/fonts/Lora/Lora-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Lora/Lora-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    #     - asset: assets/fonts/Lora/Lora-Italic.ttf
    #       style: italic
    #     - asset: assets/fonts/Lora/Lora-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Lora/Lora-MediumItalic.ttf
    #       weight: 500
    #       style: italic
    #     - asset: assets/fonts/Lora/Lora-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Lora/Lora-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Lora/Lora-SemiBoldItalic.ttf
    #       weight: 600
    #       style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis/Metropolis-Thin.otf
          weight: 200
        - asset: assets/fonts/Metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/Metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis/Metropolis-Bold.otf
          weight: 700
